export const brands = [
    "brand",
    "Al Waha",
    "Streetsmoke",
    "Dumanji",
    "Fumari",
    "Hookain",
    "Mr. Shisha",
    "Nameless",
    "Revoshi",
    "Al Fakher",
    "Shisha Kartel",
    "Blue Horse",
    "Taboo",
    "Holster",
    "Blaze",
    "Adalya",
    "Anda",
    "Overdozz",
]
