export const FlavoursListLocal = [
    "Pineapple",
    "Apple",
    "Apricot",
    "Berry",
    "Bergamot",
    "Pear",
    "Blueberry",
    "Blackberry",
    "Candy",
    "Dough",
    "Cola",
    "Cranberry",
    "Ice Cream",
    "Energy Drink",
    "Strawberry",
    "Fig",
    "Pomegranate",
    "Grapefruit",
    "Grape",
    "Raspberry",
    "Honey",
    "Ginger",
    "Jasmine",
    "Coffee",
    "Cactus",
    "Caramel",
    "Kiwi",
    "Cherry",
    "Coconut",
    "Lemon",
    "Lime",
    "Tangerine",
    "Mango",
    "Melon",
    "Menthol",
    "Mint",
    "Milk",
    "Orange",
    "Peach",
    "Passion Fruit",
    "Pistachio",
    "Plum",
    "Rose",
    "Chocolate",
    "Vanilla",
    "Tea",
    "Pie",
    "Watermelon",
    "Cinnamon",
    "Banana",
    "Cream",
    "Lychee",
    "Cookie",
    "Gum",


  ]
